### ISSUE TITLE
Integration Done: PERK ViSITS

### ISSUE THREAD

**Issue by Schlangi** [railslove/meine-checkins-backlog#10]
-     Name: PERK ViSITS
-     Example Checkin URL
1. Staging: https://visits-dev.perkiot.com/entry/9b2b0c5f-259c-438b-e0bc-08d8de26c0ad
2. Prod: https://visits.perkiot.com/entry/will-not-disclose-it-here

-     Logo (uploaded)
![PERK-ViSITS](https://user-images.githubusercontent.com/80587908/117068946-2bcdb580-ad2c-11eb-91f2-852343d78908.png)
![PERK-ViSITS_lang](https://user-images.githubusercontent.com/80587908/117068948-2c664c00-ad2c-11eb-9952-dc0614c547e0.png)

-     Example QR Code
![grafik](https://user-images.githubusercontent.com/80587908/117069093-5fa8db00-ad2c-11eb-9962-98df06d1ce78.png)

**Comment by Schlangi** [comment]
Ich darf kein Label setzen...

**Comment by stringparser** [comment]
Tested. This is working for `v1.8.3`.

Logo showed in my check-ins list item.

cc @koos

**Comment by Schlangi** [comment]
Sieht gut aus, auch das ihr noch das andere Logo genommen habt! Das ist besser für das Anzeigeformat.
