### ISSUE TITLE
Integration Done: BEVENTIO

### ISSUE THREAD

**Issue by beventio** [railslove/meine-checkins-backlog#11]
**Name**
BEVENTIO

**Logo (upload it)**
![logo-BEVENTIO](https://user-images.githubusercontent.com/68020960/117103129-0c5d7980-ad7a-11eb-9547-6666a43deaed.png)

**Example Checkin URL**
https://checkin.bevent.io/12603/IN/41420/37

**Example QR Code**
![demo-checkin-qr](https://user-images.githubusercontent.com/68020960/117103179-2434fd80-ad7a-11eb-9944-fc46e701bffb.png)

**Comment by stringparser** [comment]
Tested. This is working for `v1.8.3`.

Logo shown in my check-ins list.

cc @koos

**Comment by koos** [comment]
works for me too. closing
