### ISSUE TITLE
iOS: Betreiber-Icon wird nicht angezeigt, Betreiber App-Name falsch

### ISSUE THREAD

**Issue by marianfeiler** [railslove/meine-checkins-backlog#2]
1. Icon wird nicht angezeigt (was ist zu tun)
2. Als Name wäre gut, wenn dann auch PANDA-SAFE stehen würde (was ist zu tun)

![IMG_0906](https://user-images.githubusercontent.com/12560807/116082710-042b7d00-a69c-11eb-88ef-62cf2ae1a70e.PNG)

**Comment by koos** [comment]
@marianfeiler kannst du bitte die tickets splitten und ein bisschen besser beschreiben. und stellt bitte einen QR Code bereit mit dem wir das nachvollziehen können und testen können.

**Comment by marianfeiler** [comment]
Klar, bekomme ich hin...

**Comment by marianfeiler** [comment]
Nach Update 1.8.2 (22) bliebe noch die Frage, wie man den App Namen (in unserem Fall steht ja "pandasafe.app" da, beeinflussen kann?

Unser Logo (Icon) wird ja nun angezeigt.

**Comment by marianfeiler** [comment]
Update 1.8.2 (25)

Logo vorhanden. 

Appname sollte "PANDA·SAFE" statt "pandasafe.app" - Wie kann ich das beeinfllussen?

**Comment by marianfeiler** [comment]
Update 1.9.1 (27) 

Logo Passt, Appname passt auch, Checkin und checkout klappen auch.
