### ISSUE TITLE
Android: Kein Betreiberlogo und unpraktischer App-Name

### ISSUE THREAD

**Issue by Schlangi** [railslove/meine-checkins-backlog#7]
1. Icon wird nicht angezeigt (was ist zu tun)
2. Als Name wäre gut, wenn dann der App-Name angezeigt wird, nicht die URL (was ist zu tun)

**Comment by stringparser** [comment]
Dies hängt von die Integration durchführen. Wir müssen eine Liste bauen für das website hostname nach ein gutes Betreiberlogo und Name haben.

Ich werde heute für die neue Anbieter es machen 👍

**Comment by Schlangi** [comment]
Wird ja jetzt über die "integration-done" Tickets gemacht...
